# Step 1 (greetings)
# Step 2 (collection of orders)
# Step 3 (payment)
# Step 4 (farewell)
print("Hello, you're welcome to Sweetfingers restaurant!")
print("Take a sit, have the menu and tell us your order.")
print("Your order will be ready in 10 minutes.")
order = input("Enter your order: meatpie, doughnuts and sausage rolls")
print("Would you like to pay with a card or cash?")
print("Thank you for buying from us.")